### ISSUE TITLE
composer 安装的时候老是报错，无论是国内镜像还是国外镜像都会。能否手动安装？

### ISSUE THREAD

**Issue by X-Bird** [NauxLiu/Laravel-SendCloud#2]
hahaha git:(develop) ✗ composer require "naux/sendcloud:*"
./composer.json has been updated

> php artisan clear-compiled
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package naux/sendcloud could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Conclusion: remove laravel/framework v5.1.27
    - Conclusion: don't install laravel/framework v5.1.27
    - Can only install one of: laravel/framework[v5.1.25, v5.1.27].
    - don't install illuminate/contracts v5.1.25|don't install laravel/framework v5.1.27
    - don't install laravel/framework v5.1.27|remove illuminate/contracts v5.1.25
    - don't install illuminate/contracts v5.1.25|don't install laravel/framework v5.1.27
    - Installation request for laravel/framework == 5.1.27.0 -> satisfiable by laravel/framework[v5.1.27].
    - Installation request for illuminate/contracts == 5.1.25.0 -> satisfiable by illuminate/contracts[v5.1.25], laravel/framework[v5.1.25].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by nauxliu** [comment]
重新试下，我刚 release 了一个版本

**Comment by X-Bird** [comment]
虽然能安装了，但是好像使用不了，已经正确配置api key 和 api user 了，都不行。
提示信息是：Bad username / password!

然后我在sendcloud的开发文档又没有找到对应的错误？

所以我觉得这个错误信息应该不是sendcloud发出的，不知道是哪里出问题。
作者您能确定您的这个插件目前还能正常工作么？

**Comment by X-Bird** [comment]
然后其实 composer require "naux/sendcloud:dev-master" 就能安装了

**Comment by nauxliu** [comment]
`dd(config('services.sendcloud'))` 看下数据

**Comment by X-Bird** [comment]
明白你意思，配置是确定有的，我在 php artisan tinker 里面打出来过，也在 routes 里面dd过，都有的。

**Comment by X-Bird** [comment]
而且dd出来的配置，放在官方的php例子里面是可以跑通的。

**Comment by X-Bird** [comment]
laravel 版本号 5.1

**Comment by nauxliu** [comment]
`Bad username / password!` 这个错误是 SendCloud 接口返回的。

**Comment by X-Bird** [comment]
...
检查了又检查...
确实api key 和 api user 都没写错啊。
而且这两个配置在官方demo是能测试发送成功的。
而且这两个配置项one by one的对比过了，没复制粘贴错误。

**Comment by nauxliu** [comment]
自己再排查一下吧，我这边没办法复现。

**Comment by X-Bird** [comment]
好的 thx
