### ISSUE TITLE
请问群发邮件怎么写

### ISSUE THREAD

**Issue by pihc** [NauxLiu/Laravel-SendCloud#26]
![image](https://user-images.githubusercontent.com/17465928/56784498-59212800-6823-11e9-9110-4fed6253665f.png)
这是文档中的描述
![image](https://user-images.githubusercontent.com/17465928/56784519-6c33f800-6823-11e9-87ae-8320e8aa69bb.png)
我这么写发现不行，

**Comment by nauxliu** [comment]
不知道你这是哪儿看的文档，但是你图中写明需要对象的集合，而不是数组的集合。 
最好看看官方文档吧，或者自己追一下 Laravel 的源码，我没有太多精力维护这个项目
