### ISSUE TITLE
发现了您框架的一个问题

### ISSUE THREAD

**Issue by pihc** [NauxLiu/Laravel-SendCloud#27]
1. 带着“不能群发邮件”的疑惑翻了一下您的源码，希望您有时间可以改进一下代码，我不太会使用 Pull requests

2. 代码位置在这里，如果是数组进来使用“;”分隔一下就可以群发邮件了
![image](https://user-images.githubusercontent.com/17465928/56786026-0860fd80-682a-11e9-958e-c8a6fccabfcc.png)

**Comment by pihc** [comment]
忘了说一声谢谢！

**Comment by nauxliu** [comment]
拼装数组用 `;` 分隔多个邮箱的逻辑现在已经做了
https://github.com/nauxliu/Laravel-SendCloud/blob/master/src/SendCloudTransport.php#L120-L131

**Comment by pihc** [comment]
@nauxliu 
1. 我使用的是发送普通邮件的方式
```
 Mail::to(['xxx@163.com','xxx@foxmail.com'])->send(new \App\Mail\AnalysisMail($data));
```
2. 代码会走这个方法
![image](https://user-images.githubusercontent.com/17465928/59906999-9cbb9b00-943c-11e9-8795-3cee7e2cf6d9.png)
3. 把下面的调用的方法改成另一个就可以群发邮件了，当前的 getAddress 方法只能解析出一个邮箱
![image](https://user-images.githubusercontent.com/17465928/59907199-12c00200-943d-11e9-82dc-636998fba051.png)
希望你有时间可以看一下，我现在只能循环调用第1部里的方法来发送多人，但是我需要群发邮件的功能

**Comment by nauxliu** [comment]
确定了下，你说的是对的，能做一个 PR 吗
