### ISSUE TITLE
使用AUTH 找回密码功能的时候提示错误

### ISSUE THREAD

**Issue by liuyami** [NauxLiu/Laravel-SendCloud#4]
LARAVEL 5.1 使用自带的AUTH找回密码时提示下面错误：

Sendcloud has exception : 553 template_validate not match, reason:unequal content

**Comment by nauxliu** [comment]
你需要先在 SendCloud 添加找回密码的模板。

**Comment by liuyami** [comment]
@NauxLiu 非常感谢，我之前没用过sendcloud，想请教一下，无论发送什么邮件，一定需要先在sendcloud上建立模板吗？

**Comment by nauxliu** [comment]
是的，模板必须要通过审核才行。至于原因你懂得

**Comment by liuyami** [comment]
感谢解答 @NauxLiu
